#!/usr/bin/env bash
# Regenerates src/relay/ from a PINNED shield-relay commit.
#
# NEVER hand-edit the vendored files: fix upstream, merge there, bump PIN,
# re-run this script. The only transforms are the deterministic ones below
# (concatenating the protocol sources, rewriting the internal import path,
# and a prettier pass).
#
# Why vendoring exists at all: the relay clients declare workspace:* deps and
# cannot be installed via file:/git until they are published — tracked as
# Linear WS-92, which deletes this copy and this script in favour of a
# normal '@shield/relay-dapp-client' dependency.
set -euo pipefail

# Bump after merging upstream changes (use the shield-relay main commit).
PIN="1c390ae"

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PKG_DIR="$(cd "$SCRIPT_DIR/.." && pwd)"
OUT_DIR="$PKG_DIR/src/relay"
ROOT_DIR="$(cd "$PKG_DIR/../../../.." && pwd)"

# Locate the shield-relay checkout: explicit env var, or common sibling paths.
RELAY_DIR="${SHIELD_RELAY_DIR:-}"
if [[ -z "$RELAY_DIR" ]]; then
  for candidate in "$ROOT_DIR/../shield-relay" "$HOME/projects/shield-relay"; do
    if [[ -d "$candidate/packages/protocol" ]]; then
      RELAY_DIR="$candidate"
      break
    fi
  done
fi
if [[ -z "$RELAY_DIR" ]]; then
  echo "shield-relay checkout not found — set SHIELD_RELAY_DIR" >&2
  exit 1
fi

HEAD_SHA="$(git -C "$RELAY_DIR" rev-parse HEAD)"
if [[ "$HEAD_SHA" != "$PIN"* ]]; then
  echo "shield-relay checkout is at ${HEAD_SHA:0:12}, but the pin is $PIN." >&2
  echo "Run: git -C \"$RELAY_DIR\" checkout $PIN   (or bump PIN in this script)" >&2
  exit 1
fi
if [[ -n "$(git -C "$RELAY_DIR" status --porcelain -- packages/protocol packages/dapp-client)" ]]; then
  echo "shield-relay checkout has local modifications in the vendored packages — refusing to sync." >&2
  exit 1
fi

SRC="$RELAY_DIR/packages"

header() {
  printf '/**\n * VENDORED from ProvableHQ/shield-relay@%s (%s).\n * GENERATED by packages/aleo-wallet-adapter/wallets/shield/scripts/sync-shield-relay.sh — DO NOT EDIT BY HAND.\n * Fix upstream, merge, bump PIN, re-run. This copy is deleted when the\n * relay clients are published (Linear WS-92).\n */\n' "$PIN" "$1"
}

mkdir -p "$OUT_DIR"

{
  header "packages/protocol/src: types.ts + crypto.ts + connectUrl.ts"
  cat "$SRC/protocol/src/types.ts"
  grep -vE "from '\\./(types|connectUrl)\\.js'" "$SRC/protocol/src/crypto.ts"
  grep -vE "from '\\./(types|connectUrl)\\.js'" "$SRC/protocol/src/connectUrl.ts"
} > "$OUT_DIR/protocol.ts"

{
  header "packages/dapp-client/src/transport.ts"
  sed "s|'@shield/relay-protocol'|'./protocol'|" "$SRC/dapp-client/src/transport.ts"
} > "$OUT_DIR/transport.ts"

(cd "$ROOT_DIR" && pnpm exec prettier --write "$OUT_DIR/protocol.ts" "$OUT_DIR/transport.ts" >/dev/null)

echo "vendored shield-relay@$PIN into $OUT_DIR"
