import { Network } from './network';

/** Public deposit preparation inputs. Amounts are decimal USDC base units. */
export interface PrepareShieldedUsdcxMintOptions {
  network: Network.MAINNET | Network.TESTNET;
  sourceChain: 'ethereum' | 'ethereum-sepolia' | 'arc' | 'arc-testnet';
  amount: string;
  maxFee: string;
  /** Optional expected EVM depositor. Omit before selecting the source account. */
  depositor?: string;
  /** Any valid Aleo recipient; omitted means the connected wallet account. */
  recipient?: string;
  /** Optional application-managed retry identity. Usually generated by the adapter. */
  requestId?: string;
}

/** Provider request after the adapter has supplied a retry identity. */
export interface PrepareShieldedUsdcxMintRequest extends PrepareShieldedUsdcxMintOptions {
  requestId: string;
}

/** Public response from the wallet. Contains no user recipient or secret scalar. */
export interface PreparedShieldedUsdcxMint {
  mintId: string;
  commitmentHex: string;
  sourceChain: PrepareShieldedUsdcxMintOptions['sourceChain'];
  chainId: number;
  xReserve: string;
  deposit: {
    amount: string;
    maxFee: string;
    localToken: string;
    remoteDomain: number;
    remoteRecipient: string;
    hookData: string;
  };
}

/** Adapter result, including the generated ID for retries across reloads. */
export interface ShieldedUsdcxMintPreparation extends PreparedShieldedUsdcxMint {
  requestId: string;
}
