export { createMemoryStore } from './testing/memory-store';
/** Public synthetic vector. Never fund or use these values as wallet credentials. */
export const BLINDING_TEST_VECTOR = Object.freeze({
  programAddress: 'aleo1x7kxvcemxhlsd7x7wapwdjuyav0h6yvpe76e8fs9hmf3t53apq9s7tkyfw',
  signerAddress: 'aleo1c4ymujuysflp8uurmk5n8zrquur9pyqdhz2ty9s82prs96eydqpsfrahgf',
  viewKeyScalar: '1scalar',
  counter: 0,
  blindingFactor:
    '1486597362053800819779203635782691618849211330039711566246697090413632396910field',
  blindedAddress: 'aleo1dqleg6zkf2ca05ctxvjynzuvc4chtlqkr00m7c5yssfn7n6pd5xqj090t2',
});

/**
 * Oracle copied from the Shield wallet fixture
 * `tests/unit/fixtures/blinding-vectors.json`.
 * It was generated by the amm client, not by this package.
 */
export const SHIELD_BLINDING_VECTOR = Object.freeze({
  programAddress: 'aleo1gq2nkysj5mtz88ajgktnzwfrc6culuzeflen3dsdx26d3zzaquxseht3v7',
  signerAddress: 'aleo129pcdmuxl7naqr93g4kvmf35e3h9d8lawmn5s2cefqnww9gejvxs7s9hew',
  viewKeyScalar:
    '1791974088206979711721389196980471692298987690834480234662013578273803621808scalar',
  counter: 7,
  blindingFactor:
    '5931038762830195631510928111676633545046372925283139116232664406585431781544field',
  blindedAddress: 'aleo160qupzhw60jah608c8wngs2hln56jnkp02m8um37kh8eurs9uyys24rm2l',
});
export { runStorageContract } from './testing/store-contract';
